name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # 개인 토큰을 사용할 것인지 말 것인지
        persist-credentials: false
    - name: 1. pip 업그래이드
      run: python -m pip install --upgrade pip
    - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.1

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
          python on_upload.py $file
        done
    - name: Commit files
      run: |
        git config --local user.email "54740236+VESOC@users.noreply.github.com"
        git config --local user.name "VESOC"
        git add .
        git commit -m "Update New Article"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}